# Generated by Django 3.1.7 on 2021-02-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('name_product', models.CharField(max_length=127)),
                ('description', models.TextField(max_length=1027)),
                ('image', models.ImageField(upload_to='image/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subcategory')),
            ],
        ),
    ]
